### ISSUE TITLE
Use GIthub CLI

### ISSUE THREAD

**Issue by peterbsmith2** [codesyracuse/mentor-ship#28]
# SMART
## Specific
Use the GitHub CLI to create a pull request

## Measurable
- Github CLI is installed
- a PR has been created using the CLI

## Attainable
- [Check the docs](https://cli.github.com/manual/)

## Relevant
- It's a new way to interact with github that is fully supported by github company.

## Time-bound
- October 10, 2020

"Specific Adaptation to Imposed Demand" means that you get good at what you practice. If you read tutorials you get better at reading tutorials. If you write code you get better at writing code.

**Comment by AngelSantiagoPK** [comment]
Performed repository clone using github cli
